//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV_Entity_ASP.Net
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbCVEntityEntities : DbContext
    {
        public DbCVEntityEntities()
            : base("name=DbCVEntityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLADRE> TBLADRES { get; set; }
<<<<<<< HEAD
        public virtual DbSet<TBLCALISMALARIM> TBLCALISMALARIM { get; set; }
        public virtual DbSet<TBLHAKKIMDA> TBLHAKKIMDA { get; set; }
        public virtual DbSet<TBLILETISIM> TBLILETISIM { get; set; }
        public virtual DbSet<TBLYETENEKLER> TBLYETENEKLER { get; set; }
=======
        public virtual DbSet<TBLCALISMALARIM> TBLCALISMALARIMs { get; set; }
        public virtual DbSet<TBLHAKKIMDA> TBLHAKKIMDAs { get; set; }
        public virtual DbSet<TBLILETISIM> TBLILETISIMs { get; set; }
        public virtual DbSet<TBLYETENEKLER> TBLYETENEKLERs { get; set; }
>>>>>>> bc09f0e4f0a20e91f030221102c9791873f94846
    }
}
